### ISSUE TITLE
installing issues

### ISSUE THREAD

**Issue by kleinash** [fferri/v_repExtRosInterface#1]
Hi, 

I was wondering if you could help install this? 

1. download V-REP 
2. cd V-REP/programming/ros_packages/v_repExtRosInterface
3. mkdir external && cd external
4. git clone https://github.com/fferri/v_repStubsGen.git
5. export PYTHONPATH=$PYTHONPATH:$PWD
6. catkin_make 

> this is where I am running into issues, catkin build is not a valid command using ros, and this is not a catkin workspace. So I run 

7. python 
>> import catkin 
But then I get stuck again.. 

Thank you in advance.

**Comment by fferri** [comment]
This is not an issue of v_repExtRosInterface.

Using catkin-tools may be simpler to use than catkin_make. Install catkin-tools as described in http://catkin-tools.readthedocs.io/en/latest/installing.html and issue `catkin build`.

For issues which are specific to ROS, is better to ask in http://answers.ros.org/

**Comment by kleinash** [comment]
So the process I am using is correct so far?

**Comment by fferri** [comment]
Perhaps you didn't correctly initialize a catkin workspace, as described in the ROS tutorials

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repExtRosInterface#1
