### ISSUE TITLE
New V-REP issue

### ISSUE THREAD

**Issue by fillshad** [fferri/v_repExtRosInterface#14]
Hello.

I have actualized my V-REP and the interface's versions. Now, everytime I try to run some model using this interface, my V-REP crashes.

Here is the issue at V-REP's forum: http://www.forum.coppeliarobotics.com/viewtopic.php?f=5&t=6711

This message is just to report this bug. 
Thank you a lot for your work.

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repExtRosInterface#14
