### ISSUE TITLE
failed initialization: this plugin requires at least V-REP 3.4.0 rev9

### ISSUE THREAD

**Issue by xukuanHIT** [fferri/v_repExtRosInterface#18]
Hi, I complied succeedly, but it cannot be loaded when I start vrep ,the error is 
"Plugin 'RosInterface' : loading...
this plugin requires at least V-REP 3.4.0 rev9
Plugin 'RosInterface' : load failed (failed initialization)"
The vrep I used is newest, What should I do?

**Comment by fferri** [comment]
Which version of V-REP are you using? You can see the version in the Help->About menu.

**Comment by xukuanHIT** [comment]
V-REP PRO EDU ,Version 3.4.0(rev.1) , I should use rev9 ?

**Comment by fferri** [comment]
definitely yes

**Comment by xukuanHIT** [comment]
Can you give me a website link where I can download it ? Thank you very much !

**Comment by Coppelia** [comment]
You can download rev. 9 from here: http://www.coppeliarobotics.com/files/tmp/

**Comment by xukuanHIT** [comment]
Thank you !

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repExtRosInterface#18

**Comment by Asylbeck** [comment]
The vrep version (rev19, rev17) you provided doesn't even work on my pc:
Error: signal 11:
/home/base/V-REP_PRO_EDU_V3_4_0_Linux/libv_rep.so(_Z11_segHandleri+0x28)[0x7f55734bb448]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f55775214b0]
