### ISSUE TITLE
vrep_ros_interface cannot find package configuration file provided by VREP

### ISSUE THREAD

**Issue by Spielzeug** [fferri/v_repExtRosInterface#19]
catkin build output: https://pastebin.com/hHApbTTq

 CMAKE_SOURCE_DIR is ~/catkin_ws/src, so CMAKE_MODULE_PATH evaluates to ~/catkin_ws/src/cmake/modules

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repExtRosInterface#19
