### ISSUE TITLE
empty line causes compilation failure

### ISSUE THREAD

**Issue by Coppelia** [fferri/v_repExtRosInterface#4]
When the user edits meta/messages.txt or meta/services.txt and inadvertently leaves one line empty (e.g. the last line), then compilation fails. It took me a while to find the reason why suddenly the package wouldn't compile anymore.
Can you check if there is at least one non-space char on the lines?

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repExtRosInterface#4
