### ISSUE TITLE
fail locating several headerfiles

### ISSUE THREAD

**Issue by Josque** [fferri/v_repExtRosInterface#6]
I have ROS Jade and Vrep 3.3.2 but I don't have ros_msg_io.h and ros_srv_msg.h on my PC.
Or add these files or tell where to find them.

**Comment by fferri** [comment]
Those files are generated automatically. Did you follow the build instructions found in README.md?

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repExtRosInterface#6
